export const BOLLYWOODTRENDINGSTORIES_REQ = 'BOLLYWOODTRENDINGSTORIES_REQ';
export const BOLLYWOODTRENDINGSTORIES_SET = 'BOLLYWOODTRENDINGSTORIES_SET';
export const BOLLYWOODTRENDINGSTORIES_ERR = 'BOLLYWOODTRENDINGSTORIES_ERR';