import React from "react";

export const AdvertiseIframe = ({ style = {}, className = "" }) => {
	const site = [
		"https://longdogechallenge.com/",
		"https://alwaysjudgeabookbyitscover.com",
		"https://binarypiano.com/",
		"https://boringboringboring.com/",
		"https://cant-not-tweet-this.com/",
		"https://checkboxolympics.com/",
		"https://checkboxrace.com/",
		"https://cursoreffects.com",
		"https://dadlaughbutton.com/",
		"https://existentialcrisis.com/",
		"https://findtheinvisiblecow.com/",
		"https://greatbignothing.com/",
		"https://jacksonpollock.org/",
		"https://loopedforinfinity.com/",
		"https://mondrianandme.com/",
		"https://onesquareminesweeper.com/",
		"https://pointerpointer.com",
		"https://popcat.click/",
		"https://puginarug.com",
		"https://remoji.com/",
		"https://smashthewalls.com/",
		"https://strobe.cool/",
		"https://thatsthefinger.com/",
		"https://thepigeon.org/",
		"https://thezen.zone/",
		"https://www.bouncingdvdlogo.com/",
		"https://www.trypap.com/",
		"https://zoomquilt.org/",
		"https://bouncingdvdlogo.com/",
		"https://www.airfrais.eu/us/index.html",
		"https://www.purristan.com/",
		"https://s3.mirror.co.uk/click-the-colour-and-not-the-word/index.html",
		"https://www.gutenberg.org/",
		"https://drawception.com",
		"https://morelessgame.com/",
		"https://web.archive.org/web/20180201230730/http://www.dragomirsdiary.com/2011/08/hello-diary.html",
		"https://scatter.wordpress.com/2010/05/30/the-shortest-possible-game-of-monopoly-21-seconds/",
		"https://web.archive.org/web/20170514160422/http://manbabies.com/",
		"https://www.dctech.com/physics/notes/0005.php",
		"https://web.archive.org/web/20160725231633/http://celebritiesaskids.net/",
		"https://isitchristmas.com/",
		"https://www.youtube.com/askaninja",
		"https://www.futureme.org/",
		"https://trek.nasa.gov/mars/index.html",
		"https://onetinyhand.com/",
		"https://www.flightradar24.com/",
		"https://web.archive.org/web/20190512120348/https://oct82.com/",
		"https://ncase.me/trust/",
		"https://web.archive.org/web/20190618062455/http://www.iloveyoulikeafatladylovesapples.com/",
		"https://www.youtube.com/watch?v=9C_HReR_McQ&feature=emb_logo",
		"https://ncase.me/trust/",
		"https://youtu.be/9C_HReR_McQ",
		"https://www.housecreep.com/",
		"https://www.youtube.com/watch?v=jU9USxJ9vPs",
		"https://swatblog.rtgp.xyz/",
		"https://web.archive.org/web/20180211011023/http://cutecatnames.com/",
		"https://www.kamogo.com/9",
	][Math.floor(Math.random() * 90)]
	console.log('Displaying ad: ', site)
	return (<aside style={style} className={`inline-flex ${className}`}>
		<iframe src={site} title="ad" className="flex-1" />
	</aside>);
};
export default AdvertiseIframe