export const FITNESSTRENDINGSTORIES_REQ = 'FITNESSTRENDINGSTORIES_REQ';
export const FITNESSTRENDINGSTORIES_SET = 'FITNESSTRENDINGSTORIES_SET';
export const FITNESSTRENDINGSTORIES_ERR = 'FITNESSTRENDINGSTORIES_ERR';