export const HOLLYWOODTRENDINGTORIES_REQ = 'HOLLYWOODTRENDINGTORIES_REQ';
export const HOLLYWOODTRENDINGTORIES_SET = 'HOLLYWOODTRENDINGTORIES_SET';
export const HOLLYWOODTRENDINGTORIES_ERR = 'HOLLYWOODTRENDINGTORIES_ERR';