export const INTERNATIONALSTORIES_REQ = 'INTERNATIONALSTORIES_REQ';
export const INTERNATIONALSTORIES_SET = 'INTERNATIONALSTORIES_SET';
export const INTERNATIONALSTORIES_ERR = 'INTERNATIONALSTORIES_ERR';